repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.13
  hooks:
    # Run the linter.
    - id: ruff-check
      exclude: plugins/asset_source/netbox/src/dina/plugins/datasource/netbox/api_client
      respect-gitignore: true
    # Run the formatter.
    - id: ruff-format
      exclude: plugins/asset_source/netbox/src/dina/plugins/datasource/netbox/api_client
      respect-gitignore: true