services:
  postgres:
    image: postgres:15
    container_name: cachedb-postgres
    environment:
      POSTGRES_DB: cachedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "2345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    shm_size: 1G


volumes:
  postgres_data: