# An invalid plugin configuration

[DataSource]
plugin_name = "isduba_fetcher"
timeout_seconds = 30
update_interval = 60

[DataSource.Plugin]
url = "http://endpoint.sample.com/"
username = "username"
password = "password"
verify_ssl = true
database_host = "localhost"
database_port = 2345
database = "cachedb"
database_username = "admin"
database_password = "secret"
