# An invalid plugin configuration

[DataSource]
# The plugin name is the name used to install the extra feature when installing the asset synchronizer.
# When developing a package, please note that the package name must be `dina.plugins.datasource.<plugin_name>`
plugin_name = "isduba_fetcher"

[DataSource.Plugin]
url = "http://endpoint.sample.com/"
keycloak_url = "http://keycloak.sample.com/"
keycloak_realm = "isduba"
username = "username"
password = "password"
verify_ssl = true
