# A sample csaf synchronizer config.
# The csaf synchronizer config must always contain an [Csafsync] entry.
# The preprocessor plugins to use must be explicitly specified.
# If no preprocessing is needed, use the default identity preprocessor.

[Csafsync]
# A list of preprocessor plugins. The order in which they are provided
# here is the order in which they are executed on the data.
preprocessor_plugins = ["identity"]


[Cachedb]
host = "localhost"
port = 2345
database = "cachedb"
username = "admin"
password = "secret"