# A sample csaf synchronizer config.
# The csaf synchronizer config must always contain an [Csafsync] entry.
# The preprocessor plugins to use must be explicitly specified.
# If no preprocessing is needed, use the default identity preprocessor.

[Csafsync]
# Csaf specific configuration

[Synchronizer]
# Synchronization inetrval in seconds.
# The synchronizer will perform a fetching task every X seconds.
sync_interval = 60
# Path to the directory containing CSAF data source plugin configuration TOML files
plugin_configs_path = "./assets/plugin_configs/data_source/csaf/active/"

# A list of preprocessor plugins. The order in which they are provided
# here is the order in which they are executed on the data.
preprocessor_plugins = ["identity"]

[Synchronizer.Api]
# The address to serve on
# 0.0.0.0 means all interfaces
host = "0.0.0.0"

# The port to serve on.
port = 8001

[Cachedb]
host = "localhost"
port = 2345
database = "cachedb"
username = "admin"
password = "secret"