# Netbox plugin configuration

[DataSource]
# The plugin name is the name used to install the extra.
# The package name must be dina.plugins.datasource.<plugin_name>
plugin_name = "netbox_fetcher"
timeout_seconds = 30
update_interval = 60

[DataSource.Netbox]
# Netbox-specific configuration
api_url = "https://netbox.example.com/api"
api_token = "abcdef123456"
