# Netbox plugin configuration

[DataSource]
# The plugin name is the name used to install the extra.
# The package name must be dina.plugins.datasource.<plugin_name>
plugin_name = "netbox_fetcher"
timeout_seconds = 30
update_interval = 60

[DataSource.Netbox]
# Netbox-specific configuration
api_url = "http://172.16.15.61:8000"
api_token = "11ff5d2484c3f34b3618e4de3156ce699298bc3f"
