# An invalid plugin configuration

[DataSource]
plugin_name = "isduba_fetcher"
timeout_seconds = 30
update_interval = 60

[DataSource.ISDuBA]
url = "http://endpoint.sample.com/"
username = "username"
password = "password"
verify_ssl = True